# Generated by Django 5.0.8 on 2024-08-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniworld', '0005_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='teacher',
        ),
    ]
