# Generated by Django 5.0.8 on 2024-08-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_redacted_message_flagged'),
        ('uniworld', '0006_rename_user_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='chat.room'),
        ),
    ]
