# Generated by Django 5.0.8 on 2024-09-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniworld', '0011_rename_grade_assignmentsubmission_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
