# Generated by Django 5.0.8 on 2024-08-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flagged_categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='redacted',
            field=models.BooleanField(default=False),
        ),
    ]
