# Generated by Django 5.0.8 on 2024-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_flagged_categories_message_redacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='redacted',
            new_name='flagged',
        ),
    ]
